dbt_biera:
  outputs:
    dev:
      dbname: warehouse
      host: localhost
      pass: default
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: admin
  target: dev
  